In [4]:
import tensorflow as tf
import pandas as pd 
import numpy as np

In [11]:
tensor = tf.constant([[2,3],[4,5]])

In [12]:
tensor+5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10]], dtype=int32)>

In [13]:
tensor2 = tf.Variable([[1,1],[1,1]])

In [14]:
tensor+tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [16]:
tf.multiply(tensor,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [17]:
tf.math.add(tensor,tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>