In [1]:
import pandas as pd 
import tensorflow as tf 
import numpy as np 

2024-02-03 12:53:38.892216: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-03 12:53:38.893481: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-03 12:53:38.921784: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-03 12:53:38.922675: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-03 12:53:39.364403: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [2]:
tensor = tf.constant([[1,2],[2,4]])
tensor2 = tf.constant([[2,5],[6,9]])

2024-02-03 12:54:38.522707: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:995] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2024-02-03 12:54:38.522972: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...


In [3]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [2, 4]], dtype=int32)>

In [4]:
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 5],
       [6, 9]], dtype=int32)>

In [5]:
tf.linalg.matmul(tensor2,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[12, 24],
       [24, 48]], dtype=int32)>

In [8]:
tensor3 = tf.Variable([[1,2,5],[7,2,1],[3,3,3]])
tensor4 = tf.constant([[3,5],[6,7],[1,8]])
tf.linalg.matmul(tensor3,tensor4)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [10]:
tensor3 @ tensor4

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [13]:
x = tf.Variable([[1,2],[3,4],[5,6]])
y = tf.Variable([[7,8],[8,9],[9,10]])
x@y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 