In [1]:
import pandas as pd 
import tensorflow as tf 
import numpy as np 


2024-02-04 01:44:03.587899: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-04 01:44:03.589111: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-04 01:44:03.615679: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-04 01:44:03.616281: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-04 01:44:04.108370: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [10]:
x = tf.Variable([[1,2],[3,4],[5,6]])
y = tf.Variable([[7,8],[8,9],[9,10]])
x,y

(<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
 array([[ 7,  8],
        [ 8,  9],
        [ 9, 10]], dtype=int32)>)

In [11]:
tf.tensordot(x,tf.transpose(y),axes=0)

<tf.Tensor: shape=(3, 2, 2, 3), dtype=int32, numpy=
array([[[[ 7,  8,  9],
         [ 8,  9, 10]],

        [[14, 16, 18],
         [16, 18, 20]]],


       [[[21, 24, 27],
         [24, 27, 30]],

        [[28, 32, 36],
         [32, 36, 40]]],


       [[[35, 40, 45],
         [40, 45, 50]],

        [[42, 48, 54],
         [48, 54, 60]]]], dtype=int32)>

In [14]:
tf.reshape(x,shape=(6,-1))

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]], dtype=int32)>