In [1]:
import pandas as pd 
import tensorflow as tf 
import numpy as np

2024-02-04 08:30:57.744032: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-04 08:30:57.775544: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-04 08:30:58.028457: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2024-02-04 08:30:58.030063: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-02-04 08:30:58.674813: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not fin

In [3]:
d = tf.constant([-7,-10])

In [4]:
tf.abs(d)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [33]:
e =tf.constant(np.random.randint(0,100,size=50),dtype=tf.float64)

In [34]:
e

<tf.Tensor: shape=(50,), dtype=float64, numpy=
array([76., 24., 50., 91., 40., 82., 13., 21., 21., 72., 87.,  2., 19.,
       66., 40., 43., 29., 77., 51., 15.,  1., 38., 26., 63.,  3.,  0.,
       54., 94., 64., 36., 79., 27., 33., 97., 46., 52., 42., 14., 51.,
       26., 84., 79., 88., 84., 34., 67.,  1., 18., 41., 34.])>

In [35]:
tf.reshape(e,shape=(10,-1)).ndim


2

In [36]:
tf.reduce_min(e),tf.reduce_max(e),tf.reduce_mean(e)

(<tf.Tensor: shape=(), dtype=float64, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=97.0>,
 <tf.Tensor: shape=(), dtype=float64, numpy=45.9>)

In [37]:
np.min(e)

0.0

In [38]:
tf.math.reduce_variance(e)

<tf.Tensor: shape=(), dtype=float64, numpy=787.17>

In [41]:
tf.math.reduce_std(e)

<tf.Tensor: shape=(), dtype=float64, numpy=28.05655003737986>

In [43]:
\

AttributeError: module 'tensorflow' has no attribute 'reduce_std'